[versions]
hytale-mod-plugin = "0.+"
shadow = "9.3.0"

jetbrains-annotations = "26.0.2-1"
jspecify = "1.0.0"

guava = "33.5.0-jre"

bettermodlist = "1.+"

[libraries]
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }

guava = { module = "com.google.guava:guava", version.ref = "guava" }

bettermodlist = { module = "com.buuz135:BetterModlist", version.ref = "bettermodlist" }

[bundles]

[plugins]
hytale = { id = "hytale-mod", version.ref = "hytale-mod-plugin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
